title: Quantum Mechanics
description: Gastronote 的量子力學筆記
theme: just-the-docs

url: https://gastronote.github.io/QuantumMechanics

# 啟用數學公式支援
aux_links:
  "Gastronote 主站":
    - "https://gastronote.github.io"

# 讓數學公式生效的設定
search:
  enabled: true

# 這一行是為了讓 MathJax 運作
head_content: |
  <script type="text/javascript" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>